services:
  application:
    container_name: application
    build:
      dockerfile: ./docker/php/dockerfile.php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/logs/:/tmp/
    ports:
      - ${PORT_SERVER:-8080}:443
    networks:
      - testeInternos
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: mysql_database
    image: mariadb:10.6.16
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - /var/lib/mysql.sock
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - testeInternos

networks:
  testeInternos:
    driver: bridge

volumes:
  mysql:
    name: 'volume_mysql'
    driver: local