services:
  application:
    container_name: application
    build:
      dockerfile: ./docker/php/dockerfile.php
    volumes:
      - ./src:/var/www/html
    ports:
      - ${PORT_SERVER:-8080}:80
    networks:
      - testeInternos
  mysql_database:
    container_name: mysql_database
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - /var/lib/mysql.sock
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - testeInternos

networks:
  testeInternos:
    driver: bridge

volumes:
  mysql:
    name: 'volume_mysql'
    driver: local